package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/domehahn/skpm/v2/internal/lockfile"
	"gopkg.in/yaml.v3"
	"github.com/spf13/cobra"
)

const defaultNoticeFile = "NOTICE.md"

// noticeEntry holds the aggregated notice info for one installed skill.
type noticeEntry struct {
	Name        string
	Version     string
	License     string
	LicenseText string
}

func newNoticeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "notice",
		Short: "Aggregate LICENSE/NOTICE information for installed skills",
		Long: `Scans installed skill directories and collects license data from skill.yaml
and any LICENSE file. Useful for open-source compliance workflows.`,
	}
	cmd.AddCommand(newNoticeGenerateCmd())
	cmd.AddCommand(newNoticeCheckCmd())
	return cmd
}

func newNoticeGenerateCmd() *cobra.Command {
	var lockPath string
	var outFile string

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Write NOTICE.md aggregating license info from all installed skills",
		RunE: func(cmd *cobra.Command, args []string) error {
			if lockPath == "" {
				lockPath = lockfile.DefaultFilename
			}
			if outFile == "" {
				outFile = defaultNoticeFile
			}

			lf, err := lockfile.Read(lockPath)
			if err != nil {
				return &UserError{Message: fmt.Sprintf("read %s: %v", lockPath, err)}
			}

			entries := collectNoticeEntries(lf)

			var sb strings.Builder
			sb.WriteString("# NOTICE\n\n")
			sb.WriteString(fmt.Sprintf("This file was generated by skpm on %s.\n\n", time.Now().UTC().Format("2006-01-02")))
			sb.WriteString("---\n\n")

			for _, e := range entries {
				sb.WriteString(fmt.Sprintf("## %s  (%s)\n\n", e.Name, e.Version))
				if e.License != "" {
					sb.WriteString(fmt.Sprintf("**License:** %s\n\n", e.License))
				} else {
					sb.WriteString("**License:** (not specified)\n\n")
				}
				if e.LicenseText != "" {
					sb.WriteString("```\n")
					sb.WriteString(strings.TrimSpace(e.LicenseText))
					sb.WriteString("\n```\n\n")
				}
				sb.WriteString("---\n\n")
			}

			out := sb.String()

			if globalDryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "Dry run: would write %s (%d skill(s))\n", outFile, len(entries))
				return nil
			}
			if err := os.WriteFile(outFile, []byte(out), 0o644); err != nil {
				return &InternalError{Message: "write NOTICE file", Cause: err}
			}
			fmt.Fprintf(cmd.OutOrStdout(), "NOTICE written to %s (%d skill(s))\n", outFile, len(entries))
			return nil
		},
	}

	cmd.Flags().StringVar(&lockPath, "lock", "", "Lockfile path (default: agent-skills.lock)")
	cmd.Flags().StringVarP(&outFile, "out", "f", "", "Output file (default: NOTICE.md)")
	return cmd
}

func newNoticeCheckCmd() *cobra.Command {
	var lockPath string
	var requireLicense bool

	cmd := &cobra.Command{
		Use:   "check",
		Short: "Check that every installed skill declares a license",
		RunE: func(cmd *cobra.Command, args []string) error {
			if lockPath == "" {
				lockPath = lockfile.DefaultFilename
			}

			lf, err := lockfile.Read(lockPath)
			if err != nil {
				return &UserError{Message: fmt.Sprintf("read %s: %v", lockPath, err)}
			}

			entries := collectNoticeEntries(lf)

			type result struct {
				Skill   string `json:"skill"`
				Version string `json:"version"`
				License string `json:"license"`
				Status  string `json:"status"`
			}

			var results []result
			missing := 0
			for _, e := range entries {
				status := "ok"
				if e.License == "" {
					status = "missing"
					missing++
				}
				results = append(results, result{
					Skill:   e.Name,
					Version: e.Version,
					License: e.License,
					Status:  status,
				})
			}

			format := outputFormat()
			if format == OutputJSON {
				PrintResult(format, CommandResult{
					Success: missing == 0 || !requireLicense,
					Command: "notice check",
					Data:    results,
				})
				if requireLicense && missing > 0 {
					return &UserError{Message: fmt.Sprintf("%d skill(s) have no declared license", missing)}
				}
				return nil
			}

			for _, r := range results {
				icon := "✓"
				lic := r.License
				if r.Status == "missing" {
					icon = "?"
					lic = "(not declared)"
				}
				fmt.Fprintf(cmd.OutOrStdout(), "  %s  %-28s  %-12s  %s\n", icon, r.Skill+"@"+r.Version, lic, r.Status)
			}
			if missing > 0 {
				fmt.Fprintf(cmd.OutOrStdout(), "\n%d of %d skill(s) have no declared license\n", missing, len(results))
			} else {
				fmt.Fprintf(cmd.OutOrStdout(), "\nAll %d skill(s) declare a license\n", len(results))
			}

			if requireLicense && missing > 0 {
				return &UserError{Message: fmt.Sprintf("%d skill(s) have no declared license", missing)}
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&lockPath, "lock", "", "Lockfile path (default: agent-skills.lock)")
	cmd.Flags().BoolVar(&requireLicense, "require", false, "Fail when any skill has no license declared")
	return cmd
}

// collectNoticeEntries scans each skill's InstalledTo paths to find skill.yaml
// and a LICENSE file, then returns a deduplicated slice sorted by skill name.
func collectNoticeEntries(lf *lockfile.LockFile) []noticeEntry {
	seen := make(map[string]bool)
	var entries []noticeEntry

	for _, sl := range lf.Skills {
		if seen[sl.Name] {
			continue
		}
		seen[sl.Name] = true

		e := noticeEntry{
			Name:    sl.Name,
			Version: sl.Version,
		}

		// Try each InstalledTo path to find skill.yaml and a LICENSE file.
		for _, installPath := range sl.InstalledTo {
			if e.License == "" {
				e.License = licenseFromSkillYAML(installPath)
			}
			if e.LicenseText == "" {
				e.LicenseText = licenseTextFromDir(installPath)
			}
			if e.License != "" && e.LicenseText != "" {
				break
			}
		}

		entries = append(entries, e)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})
	return entries
}

func licenseFromSkillYAML(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "skill.yaml"))
	if err != nil {
		return ""
	}
	var m struct {
		License string `yaml:"license"`
	}
	if yaml.Unmarshal(data, &m) != nil {
		return ""
	}
	return strings.TrimSpace(m.License)
}

func licenseTextFromDir(dir string) string {
	candidates := []string{"LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE"}
	for _, name := range candidates {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err == nil {
			return string(data)
		}
	}
	return ""
}
